server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/routemind
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    com.routemind.orderkit: debug
springdoc:
  api-docs:
    path: /v1/api-routemind-docs